version: "3"

services:
  web:
    image: kayeet-game-server
    volumes:
     - .:/usr/src/app
    ports:
      - "1647:1647"
    networks:
      - traefik_proxy_net
#    labels:
#     - traefik.enable=true
#     - traefik.http.services.kayeet-webhost.loadbalancer.server.port=80
#     - traefik.http.routers.kayeet-webhost-router.entrypoints=websecure
#     - traefik.http.routers.kayeet-webhost-router.tls.certresolver=main-resolver
#     - traefik.http.routers.kayeet-webhost-router.rule=Host(`kayeet.me`)

networks:
  traefik_proxy_net:  # connects to the traefik proxy that is part of the ERPNext docker-compose setup
    external: true
